services:
  javaapp:
    build: .
    container_name: java-app
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://69.62.81.203:5433/pg_play
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postres
    extra_hosts:
      - "skyva_db:69.62.81.203"  # Optional: creates hostname alias